ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password

jwt:
  issuer: "http://127.0.0.1:8080"
  domain: "http://127.0.0.1:8080"
  audience: "users"
  realm: "schedule api"