ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    host: 172.20.10.2
    port: 5555
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password

jwt:
  issuer: "http://172.20.10.2:5555"
  domain: "http://172.20.10.2:5555"
  audience: "users"
  realm: "schedule api"

  #172.20.10.2
  #192.168.1.5